version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/zombie-royale
hooks: 
#  BeforeInstall:
#    - location: scripts/install_dependencies.sh
#      timeout: 300
#      runas: root
 AfterInstall:
   - location: startup.sh
     timeout: 300
#  ApplicationStart:
#    - location: /home/ubuntu/app/startup.sh
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: root
